blacklist:
  - damn
  - darn
  - sped

quips:
  - Do you talk to your grandma like that?
  - What would meemaw think of your language.
  - You should be embarrased!
  - I'm not mad, I'm just disappointed.