word_lists: 

  watchword: 
    - "stupid"

  scoldword: 
    - "damn"
    - "darn"
    - "retard"

  kickword:
    - "crap"

  autokickword:
    - "sped"

rep-start: 100

rep-kick: 
  - 90
  - 80
  - 70
  - 60
  - 50
  - 40
  - 30
  - 20
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

scolds: 
  - "Do you talk to your grandma like that?"
  - "What would meemaw think of your language."
  - "You should be embarrased!"
  - "I'm not mad, I'm just disappointed."
  - "Bruh."